### ISSUE TITLE
Request for Feedback

### ISSUE THREAD

**Issue by jeremeamia** [awslabs/aws-sdk-php-resources#1]
Thanks for taking a look at the AWS Resource APIs for PHP. We'd love it if you would provide some feedback and share any ideas you might have to improve the project.

**Comment by skyzyx** [comment]
- Aside from only having partial service coverage, the code itself looks straightforward and easy enough to use.
- Documenting the resource relationships would be very valuable (e.g., S3: Regions → Buckets → Objects). Some kind of auto-generated chart/graph to go along with the API docs would be swell.
- Including Regions at the top of the hierarchy could be valuable, including helpers for iterating and/or performing actions cross-region (e.g., duplicating S3 buckets across regions, copying an EC2 keypair across regions for re-usability).
- Providing a CLI-based SDK Console would be great. Something built on-top of Boris, which autoloads your CLI config and your `~/.borisrc` file (providing a pre-instantiated `$aws` variable), and makes it easy to pull-up and inspect the resources and response types of the resource-oriented interface. Great for debugging, and doesn't have (much) overlap with the Unified AWS CLI Tools.
- Of course, providing well-documented resource models with strong types (i.e., _shapes_) would make it easier for those of us who build in-house tools for managing AWS when the official AWS Console just doesn't cut it.
- There isn't much documentation about how to use JMESPath for more complex use cases. Sure, we can figure it out, but documentation with complex examples and a step-by-step breakdown of the query would be awesome.
- In some cases, JMESPath does more than I want it to. I often don't want to get back scalars and arrays — rather, I want to get back a more powerful _Collection_-like object that has support for map/filter/intersect built-in, allowing me to work with responses in fewer lines, without falling back to crappy PHP array functions (haystack-needle placement, anyone?). More SPL PHP, less Rasmus PHP.

**Comment by skyzyx** [comment]
Stuff that is definitely out of scope for the PHP SDK team, but which should be shared with the DP&T team as a whole.

* Managing complex permissions in IAM is a fustercluck. As a non-admin, IAM user with "Power User" permissions minus IAM management, I can't even change my own IAM password. The IAM Console is a ************* disaster for managing finely-grained permissions. The reason I bring it up here is because I don't expect that the IAM Console team will _ever_ get it right. If, perhaps, there were a saner way to manage finely-grained IAM permissions from code, we (i.e., my company and I) could build a replacement IAM console which sidesteps the disaster in the AWS Console.

* And lastly (and most certainly out of scope) is the CloudFormer tool. Last I used it, it produced a broken CloudFormation template for my infrastructure. It would be swell to have a tool which gave me a valid CloudFormation template, and actually understood things like Elastic Beanstalk and OpsWorks environments, and resolved the resource relationships appropriately. This would make it _far_ easier to build my infrastructure via the AWS Console, export a CloudFormation template, then deploy that template to a new region and add it to my Route 53 DNS routing.

**Comment by jeremeamia** [comment]
_@skyzyx Note: I removed your 2nd comment, since it was unrelated to this project, but I have passed that feedback along._

**Comment by jeremeamia** [comment]
> Aside from only having partial service coverage, the code itself looks straightforward and easy enough to use.

Thanks. We'll keep working on it. Service coverage will continue to evolve over time. Any services you are more interested in than others?

> Documenting the resource relationships would be very valuable (e.g., S3: Regions → Buckets → Objects). Some kind of auto-generated chart/graph to go along with the API docs would be swell.

Yeah, I'll be cooking up docs over the coming weeks. A chart/graph is an interesting idea! I'll definitely keep that in mind.

> Including Regions at the top of the hierarchy could be valuable, including helpers for iterating and/or performing actions cross-region (e.g., duplicating S3 buckets across regions, copying an EC2 keypair across regions for re-usability).

Good idea as well. I'll play around with that.

> Providing a CLI-based SDK Console would be great. Something built on-top of Boris, which autoloads your CLI config and your ~/.borisrc file (providing a pre-instantiated $aws variable), and makes it easy to pull-up and inspect the resources and response types of the resource-oriented interface. Great for debugging, and doesn't have (much) overlap with the Unified AWS CLI Tools.

Thought about it before, but I've never been able to prioritize it. I'd probably create it as a separate project though if I got around to it or if we started getting more requests for something like it.

> Of course, providing well-documented resource models with strong types (i.e., shapes) would make it easier for those of us who build in-house tools for managing AWS when the official AWS Console just doesn't cut it.

What do you mean by strong types/shapes?

> There isn't much documentation about how to use JMESPath for more complex use cases. Sure, we can figure it out, but documentation with complex examples and a step-by-step breakdown of the query would be awesome.

We'll add more of that as we do docs for V3

> In some cases, JMESPath does more than I want it to. I often don't want to get back scalars and arrays — rather, I want to get back a more powerful Collection-like object that has support for map/filter/intersect built-in, allowing me to work with responses in fewer lines, without falling back to crappy PHP array functions (haystack-needle placement, anyone?). More SPL PHP, less Rasmus PHP.

Arrays provide the most flexibility though. There are too many differing opinions on how collection objects in PHP should be. I personally don't like `ArrayObject`, for example. It's for the for the user to write a wrapper class/function that puts the data into the collection you like best: `function search($path, $data) {return new Collection(JmesPath\Env::search($path, $data));}`.

**Comment by jeremeamia** [comment]
Closing, since it's been a while. Feedback noted though.
